// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.11.4
// source: proto/http.proto

package http

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Request_Name int32

const (
	Request_UNKNOWN   Request_Name = 0
	Request_REQUEST_A Request_Name = 1
	Request_REQUEST_B Request_Name = 2
	Request_REQUEST_C Request_Name = 3
)

// Enum value maps for Request_Name.
var (
	Request_Name_name = map[int32]string{
		0: "UNKNOWN",
		1: "REQUEST_A",
		2: "REQUEST_B",
		3: "REQUEST_C",
	}
	Request_Name_value = map[string]int32{
		"UNKNOWN":   0,
		"REQUEST_A": 1,
		"REQUEST_B": 2,
		"REQUEST_C": 3,
	}
)

func (x Request_Name) Enum() *Request_Name {
	p := new(Request_Name)
	*p = x
	return p
}

func (x Request_Name) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Request_Name) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_http_proto_enumTypes[0].Descriptor()
}

func (Request_Name) Type() protoreflect.EnumType {
	return &file_proto_http_proto_enumTypes[0]
}

func (x Request_Name) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Request_Name.Descriptor instead.
func (Request_Name) EnumDescriptor() ([]byte, []int) {
	return file_proto_http_proto_rawDescGZIP(), []int{0, 0}
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqA *RequestA `protobuf:"bytes,100,opt,name=req_a,json=reqA,proto3" json:"req_a,omitempty"`
	ReqB *RequestB `protobuf:"bytes,101,opt,name=req_b,json=reqB,proto3" json:"req_b,omitempty"`
	ReqC *RequestC `protobuf:"bytes,102,opt,name=req_c,json=reqC,proto3" json:"req_c,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_http_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_http_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_proto_http_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetReqA() *RequestA {
	if x != nil {
		return x.ReqA
	}
	return nil
}

func (x *Request) GetReqB() *RequestB {
	if x != nil {
		return x.ReqB
	}
	return nil
}

func (x *Request) GetReqC() *RequestC {
	if x != nil {
		return x.ReqC
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResA *ResponseA `protobuf:"bytes,100,opt,name=res_a,json=resA,proto3" json:"res_a,omitempty"`
	ResB *ResponseB `protobuf:"bytes,101,opt,name=res_b,json=resB,proto3" json:"res_b,omitempty"`
	ResC *ResponseC `protobuf:"bytes,102,opt,name=res_c,json=resC,proto3" json:"res_c,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_http_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_http_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_http_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetResA() *ResponseA {
	if x != nil {
		return x.ResA
	}
	return nil
}

func (x *Response) GetResB() *ResponseB {
	if x != nil {
		return x.ResB
	}
	return nil
}

func (x *Response) GetResC() *ResponseC {
	if x != nil {
		return x.ResC
	}
	return nil
}

// req/res A
type RequestA struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *RequestA) Reset() {
	*x = RequestA{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_http_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestA) ProtoMessage() {}

func (x *RequestA) ProtoReflect() protoreflect.Message {
	mi := &file_proto_http_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestA.ProtoReflect.Descriptor instead.
func (*RequestA) Descriptor() ([]byte, []int) {
	return file_proto_http_proto_rawDescGZIP(), []int{2}
}

func (x *RequestA) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type ResponseA struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *ResponseA) Reset() {
	*x = ResponseA{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_http_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseA) ProtoMessage() {}

func (x *ResponseA) ProtoReflect() protoreflect.Message {
	mi := &file_proto_http_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseA.ProtoReflect.Descriptor instead.
func (*ResponseA) Descriptor() ([]byte, []int) {
	return file_proto_http_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseA) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

// req/res B
type RequestB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *RequestB) Reset() {
	*x = RequestB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_http_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestB) ProtoMessage() {}

func (x *RequestB) ProtoReflect() protoreflect.Message {
	mi := &file_proto_http_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestB.ProtoReflect.Descriptor instead.
func (*RequestB) Descriptor() ([]byte, []int) {
	return file_proto_http_proto_rawDescGZIP(), []int{4}
}

func (x *RequestB) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type ResponseB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *ResponseB) Reset() {
	*x = ResponseB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_http_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseB) ProtoMessage() {}

func (x *ResponseB) ProtoReflect() protoreflect.Message {
	mi := &file_proto_http_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseB.ProtoReflect.Descriptor instead.
func (*ResponseB) Descriptor() ([]byte, []int) {
	return file_proto_http_proto_rawDescGZIP(), []int{5}
}

func (x *ResponseB) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

// req/res C
type RequestC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *RequestC) Reset() {
	*x = RequestC{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_http_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestC) ProtoMessage() {}

func (x *RequestC) ProtoReflect() protoreflect.Message {
	mi := &file_proto_http_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestC.ProtoReflect.Descriptor instead.
func (*RequestC) Descriptor() ([]byte, []int) {
	return file_proto_http_proto_rawDescGZIP(), []int{6}
}

func (x *RequestC) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type ResponseC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *ResponseC) Reset() {
	*x = ResponseC{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_http_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseC) ProtoMessage() {}

func (x *ResponseC) ProtoReflect() protoreflect.Message {
	mi := &file_proto_http_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseC.ProtoReflect.Descriptor instead.
func (*ResponseC) Descriptor() ([]byte, []int) {
	return file_proto_http_proto_rawDescGZIP(), []int{7}
}

func (x *ResponseC) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

var File_proto_http_proto protoreflect.FileDescriptor

var file_proto_http_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x16, 0x64, 0x72, 0x61, 0x6b, 0x65, 0x6a, 0x69, 0x6e, 0x2e, 0x65, 0x78, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x68, 0x74, 0x74, 0x70, 0x22, 0xf0, 0x01, 0x0a, 0x07, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x05, 0x72, 0x65, 0x71, 0x5f, 0x61, 0x18,
	0x64, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x64, 0x72, 0x61, 0x6b, 0x65, 0x6a, 0x69, 0x6e,
	0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x41, 0x52, 0x04, 0x72, 0x65, 0x71, 0x41, 0x12, 0x35, 0x0a,
	0x05, 0x72, 0x65, 0x71, 0x5f, 0x62, 0x18, 0x65, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x64,
	0x72, 0x61, 0x6b, 0x65, 0x6a, 0x69, 0x6e, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73,
	0x2e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x52, 0x04,
	0x72, 0x65, 0x71, 0x42, 0x12, 0x35, 0x0a, 0x05, 0x72, 0x65, 0x71, 0x5f, 0x63, 0x18, 0x66, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x64, 0x72, 0x61, 0x6b, 0x65, 0x6a, 0x69, 0x6e, 0x2e, 0x65,
	0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x43, 0x52, 0x04, 0x72, 0x65, 0x71, 0x43, 0x22, 0x40, 0x0a, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00,
	0x12, 0x0d, 0x0a, 0x09, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x41, 0x10, 0x01, 0x12,
	0x0d, 0x0a, 0x09, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x42, 0x10, 0x02, 0x12, 0x0d,
	0x0a, 0x09, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x43, 0x10, 0x03, 0x22, 0xb2, 0x01,
	0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x05, 0x72, 0x65,
	0x73, 0x5f, 0x61, 0x18, 0x64, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x64, 0x72, 0x61, 0x6b,
	0x65, 0x6a, 0x69, 0x6e, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x68, 0x74,
	0x74, 0x70, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x41, 0x52, 0x04, 0x72, 0x65,
	0x73, 0x41, 0x12, 0x36, 0x0a, 0x05, 0x72, 0x65, 0x73, 0x5f, 0x62, 0x18, 0x65, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x21, 0x2e, 0x64, 0x72, 0x61, 0x6b, 0x65, 0x6a, 0x69, 0x6e, 0x2e, 0x65, 0x78, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x52, 0x04, 0x72, 0x65, 0x73, 0x42, 0x12, 0x36, 0x0a, 0x05, 0x72, 0x65,
	0x73, 0x5f, 0x63, 0x18, 0x66, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x64, 0x72, 0x61, 0x6b,
	0x65, 0x6a, 0x69, 0x6e, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x68, 0x74,
	0x74, 0x70, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x52, 0x04, 0x72, 0x65,
	0x73, 0x43, 0x22, 0x20, 0x0a, 0x08, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x41, 0x12, 0x14,
	0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x22, 0x21, 0x0a, 0x09, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x41, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x20, 0x0a, 0x08, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x42, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x21, 0x0a, 0x09, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x20, 0x0a, 0x08,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x21,
	0x0a, 0x09, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x12, 0x14, 0x0a, 0x05, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72,
	0x79, 0x42, 0x30, 0x0a, 0x1a, 0x63, 0x6f, 0x6d, 0x2e, 0x64, 0x72, 0x61, 0x6b, 0x65, 0x6a, 0x69,
	0x6e, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x68, 0x74, 0x74, 0x70, 0x42,
	0x04, 0x48, 0x54, 0x54, 0x50, 0x50, 0x01, 0x5a, 0x0a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68,
	0x74, 0x74, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_http_proto_rawDescOnce sync.Once
	file_proto_http_proto_rawDescData = file_proto_http_proto_rawDesc
)

func file_proto_http_proto_rawDescGZIP() []byte {
	file_proto_http_proto_rawDescOnce.Do(func() {
		file_proto_http_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_http_proto_rawDescData)
	})
	return file_proto_http_proto_rawDescData
}

var file_proto_http_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_http_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_http_proto_goTypes = []interface{}{
	(Request_Name)(0), // 0: drakejin.examples.http.Request.Name
	(*Request)(nil),   // 1: drakejin.examples.http.Request
	(*Response)(nil),  // 2: drakejin.examples.http.Response
	(*RequestA)(nil),  // 3: drakejin.examples.http.RequestA
	(*ResponseA)(nil), // 4: drakejin.examples.http.ResponseA
	(*RequestB)(nil),  // 5: drakejin.examples.http.RequestB
	(*ResponseB)(nil), // 6: drakejin.examples.http.ResponseB
	(*RequestC)(nil),  // 7: drakejin.examples.http.RequestC
	(*ResponseC)(nil), // 8: drakejin.examples.http.ResponseC
}
var file_proto_http_proto_depIdxs = []int32{
	3, // 0: drakejin.examples.http.Request.req_a:type_name -> drakejin.examples.http.RequestA
	5, // 1: drakejin.examples.http.Request.req_b:type_name -> drakejin.examples.http.RequestB
	7, // 2: drakejin.examples.http.Request.req_c:type_name -> drakejin.examples.http.RequestC
	4, // 3: drakejin.examples.http.Response.res_a:type_name -> drakejin.examples.http.ResponseA
	6, // 4: drakejin.examples.http.Response.res_b:type_name -> drakejin.examples.http.ResponseB
	8, // 5: drakejin.examples.http.Response.res_c:type_name -> drakejin.examples.http.ResponseC
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_http_proto_init() }
func file_proto_http_proto_init() {
	if File_proto_http_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_http_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_http_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_http_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestA); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_http_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseA); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_http_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_http_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_http_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestC); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_http_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseC); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_http_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_http_proto_goTypes,
		DependencyIndexes: file_proto_http_proto_depIdxs,
		EnumInfos:         file_proto_http_proto_enumTypes,
		MessageInfos:      file_proto_http_proto_msgTypes,
	}.Build()
	File_proto_http_proto = out.File
	file_proto_http_proto_rawDesc = nil
	file_proto_http_proto_goTypes = nil
	file_proto_http_proto_depIdxs = nil
}
